### ISSUE TITLE
请求失败，未知错误，中断下载

### ISSUE THREAD

**Issue by zoenbo** [Jon-Millent/dangdang-bug#1]
大佬，总是会中断失败，提示“请求失败，未知错误”，这个怎么解决呢？

**Comment by Jon-Millent** [comment]
对于免费图书和买过的书，这个提示是正常的，因为当当有频率和token到期的验证之类的，直接重复执行下载，会从上次的地方开始下载，多重复几次就下载完了。😁后续时间我会解决下这个问题。

**Comment by Jon-Millent** [comment]
你好，刚才我看了下代码，发现问题了，我明天解决下

**Comment by zoenbo** [comment]
> 你好，刚才我看了下代码，发现问题了，我明天解决下

好的

**Comment by Jon-Millent** [comment]
你好已经修复 `npm install dangdang-bug -g` 更新一下版本

**Comment by zoenbo** [comment]
> 你好已经修复 `npm install dangdang-bug -g` 更新一下版本

更新了，简直太完美了，超级感谢大佬~~大佬万岁~~！
